### ISSUE TITLE
Is it possible to build voxels game on android and iOS devices

### ISSUE THREAD

**Issue by codingwatching** [skishore/voxels#1]
Hi @skishore 
I just try to run voxels on the web browser and it runs very smooth! An awesome project!
With that performance, I really think it can run on android and iOS devices.
Is there any way to wrap or build to make the game run on android and iOS devices? 
Thank for giving it free, It is really awesome framework to start with!

**Comment by skishore** [comment]
The engine already sort of works on mobile browsers. Try loading the page on your phone. I do see that there are some issues, though. Touch events on a phone are different from mouse events on a desktop browser, so those would have to change, and it looks like the mobile browser has much lower resource limits, so draw distance would have to drop.

I'm not planning to make these changes myself. If you're interested, and you can get it the demo working on mobile web, I can review a pull request.

As for a mobile native version - that's a tall order. I've already lost whole projects because I can't keep up with the requirements to deploy native apps to Android and iOS, so I am not going to keep developing for platforms where code that works today might break tomorrow.

**Comment by codingwatching** [comment]
Hi @skishore 
I see the point
Maybe I will try to convert this project to other engines that support mobile. I hope you can help me to understand Algorithmic in your code!
Thank you for this awesome project!
